name: Test Suite

on:
  [push, pull_request]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}, JDK ${{ matrix.java }}

    strategy:
      matrix:
        java: [ '21' ]
        os: [ 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Move and verify PraxisCORE
        run: |
          mv ./praxiscore-bin/target/praxiscore ./
          ./praxiscore/bin/praxis --show-environment
      - name: Run Test Suite
        run: ./praxiscore/bin/praxis -f ./testsuite/

